AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - '**/*_spec.rb'
    - 'spec'

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Max: 500
  IgnoreCopDirectives: true
  Exclude:
    - 'rudder_analytics_sync.gemspec'

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
