AllCops:
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*_spec.rb'
    - 'example/**/*.rb'

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 200
  IgnoreCopDirectives: true
  Exclude:
    - 'rudder_analytics_sync.gemspec'

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Max: 200

Style/IfUnlessModifier:
  Enabled: false