require: rubocop-rspec

AllCops:
  NewCops: enable
  Exclude:
    - 'spec/**/*'
    - 'example/**/*'

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'example/**/*'

Style/OptionalBooleanParameter:
  Exclude:
    - 'spec/**/*'
    - 'example/**/*'

Style/FormatStringToken:
  Enabled: false

Layout/LineLength:
  Max: 200
  IgnoreCopDirectives: true
  Exclude:
    - 'rudder_analytics_sync.gemspec'

Style/Documentation:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false

Metrics/MethodLength:
  Max: 200

Style/IfUnlessModifier:
  Enabled: false