name: Code Quality Checks
on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize']

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
        
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
        with:
          egress-policy: audit

      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
      - name: Set up Ruby
        uses: ruby/setup-ruby@d5126b9b3579e429dd52e51e68624dda2e05be25 # v1.267.0
        with:
          ruby-version: '2.7'
          bundler-cache: true
      - name: Install dependencies
        run: bundle install
      - name: Run tests
        run: bundle exec rake
      # - name: Install rubocop
      #   run: gem install rubocop
      # - name: Install rubocop-rspec
      #   run: gem install rubocop-rspec
      # - name: Install rubocop-performance
      #   run: gem install rubocop-performance
      # - name: Install rubocop-rails
      #   run: gem install rubocop-rails
      # - name: Execute linting
      #   run: bundle exec rubocop
