name: Code Quality Checks
on:
  pull_request:
    branches: ['master']
    types: ['opened', 'reopened', 'synchronize']

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '3.1', '3.0', '2.7' ]
        
    steps:
      - uses: actions/checkout@v3
      - name: Set up Ruby ${{ matrix.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Run tests
        run: bundle exec rake